# Generated by Django 4.0.4 on 2022-04-30 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feed', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('bio', models.CharField(default='', max_length=500)),
                ('verified', models.BooleanField(default=False)),
                ('dp', models.ImageField(blank=True, null=True, upload_to=users.models.dp_path)),
                ('close_friends', models.ManyToManyField(blank=True, related_name='close_friend_of', related_query_name='close_friend_of', to='users.profile')),
                ('followers', models.ManyToManyField(blank=True, related_name='following', related_query_name='following', to='users.profile')),
                ('req_rec', models.ManyToManyField(blank=True, related_name='req_sent', related_query_name='req_sent', to='users.profile')),
                ('saved_posts', models.ManyToManyField(blank=True, related_name='saved_by', related_query_name='saved_by', to='feed.post')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
