# Generated by Django 4.0.4 on 2022-04-30 14:51

import datetime
from django.db import migrations, models
import django.db.models.deletion
import feed.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('feed', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to=feed.models.post_path),
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timedate', models.DateTimeField(default=datetime.datetime)),
                ('image', models.ImageField(blank=True, null=True, upload_to=feed.models.post_path)),
                ('close', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feed.post')),
                ('seen', models.ManyToManyField(blank=True, related_name='seen_stories', related_query_name='seen_stories', to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timedate', models.DateTimeField(default=datetime.datetime)),
                ('category', models.CharField(choices=[('1', 'tagged in a post'), ('2', 'tagged in a comment'), ('3', 'liked your post'), ('4', 'commented on your post'), ('5', 'started following you')], max_length=20)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feed.comment')),
                ('of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', related_query_name='activity', to='users.profile')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feed.post')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_activity', related_query_name='in_activity', to='users.profile')),
            ],
        ),
    ]
